import { useEffect, useRef, useState } from 'react'
import type { ChangeEvent, CSSProperties } from 'react'
import { discoverLocalOllama, generateAiCopy, initialOllamaUrl, isHeicFile, listOllamaModels, RECOMMENDED_VISION_MODELS, selectVisionModel, supportsVision } from './ai'
import type { AiCopy, AiProviderId, OllamaModel } from './ai'
import { chromeAiAvailabilityMessage, generateChromeAiCopy, prepareChromeAi } from './chrome-ai'
import type { ChromeAiAvailability } from './chrome-ai'
import { normalizeImageFile } from './image'
import { getInitialLanguage, translate } from './i18n'
import type { Language } from './i18n'
import { VIDEO_FORMATS, VIDEO_PATTERNS, VIDEO_QUALITIES, getFrameState, getPatternFrame, getVideoFormat, getVideoPattern, getVideoQuality, isVideoFormatId, isVideoPatternId, isVideoQualityId, minSecondsPerImage, moveItem } from './reel'
import type { PatternFrame, VideoFormatId, VideoPattern, VideoPatternId, VideoQualityId } from './reel'
import { pickVideoCodec, renderMp4, renderWebm } from './video-export'

type TextPosition = 'upper' | 'center' | 'lower'
type Slide = { id: string; name: string; url: string; image: HTMLImageElement; blob: Blob; title: string; cta: string; showText: boolean; textPosition: TextPosition }
function cover(ctx: CanvasRenderingContext2D, image: HTMLImageElement, width: number, height: number, scale = 1) { const ratio = Math.max(width / image.naturalWidth, height / image.naturalHeight) * scale; const w = image.naturalWidth * ratio; const h = image.naturalHeight * ratio; ctx.drawImage(image, (width - w) / 2, (height - h) / 2, w, h) }
function patternTransform(frame: PatternFrame) { return `translate(${frame.translateX}%, ${frame.translateY}%) rotate(${frame.rotation}deg) scale(${frame.scale})` }
// Each pattern's signature decoration, so the five looks read as distinct edits rather than the
// same pan/zoom with different numbers. Mirrored in the live preview via CSS (see styles.css).
function decorate(ctx: CanvasRenderingContext2D, pattern: VideoPattern, frame: PatternFrame, width: number, height: number) {
  if (pattern.decoration === 'letterbox') { const bar = height * .045; ctx.fillStyle = '#050408'; ctx.fillRect(0, 0, width, bar); ctx.fillRect(0, height - bar, width, bar) }
  if (pattern.decoration === 'vignette' || pattern.decoration === 'frame') { const radial = ctx.createRadialGradient(width / 2, height * .45, height * .26, width / 2, height * .45, height * .72); radial.addColorStop(0, 'rgba(0,0,0,0)'); radial.addColorStop(1, pattern.decoration === 'frame' ? 'rgba(43,24,10,.55)' : 'rgba(0,0,0,.5)'); ctx.fillStyle = radial; ctx.fillRect(0, 0, width, height) }
  if (pattern.decoration === 'badge') { ctx.save(); ctx.translate(width * .88, height * .16); ctx.scale(frame.textScale, frame.textScale); ctx.fillStyle = pattern.accent; ctx.beginPath(); ctx.arc(0, 0, width * .045, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#0d0c12'; ctx.font = `700 ${Math.round(width * .05)}px system-ui, sans-serif`; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText('✦', 0, 0); ctx.restore() }
}
function drawFrame(ctx: CanvasRenderingContext2D, slide: Slide, progress: number, title: string, cta: string, patternId: VideoPatternId, formatId: VideoFormatId, index: number) {
  const { width, height } = ctx.canvas; const frame = getPatternFrame(patternId, progress, index); const pattern = getVideoPattern(patternId); const format = getVideoFormat(formatId)
  ctx.fillStyle = '#09080d'; ctx.fillRect(0, 0, width, height); ctx.save(); ctx.globalAlpha = frame.imageOpacity; ctx.filter = pattern.filter; ctx.translate(width / 2 + width * frame.translateX / 100, height / 2 + height * frame.translateY / 100); ctx.rotate(frame.rotation * Math.PI / 180); ctx.translate(-width / 2, -height / 2); cover(ctx, slide.image, width, height, frame.scale); ctx.restore()
  decorate(ctx, pattern, frame, width, height)
  const gradient = ctx.createLinearGradient(0, height * .36, 0, height); gradient.addColorStop(0, 'rgba(8,7,13,0)'); gradient.addColorStop(1, `rgba(8,7,13,${frame.overlayOpacity})`); ctx.fillStyle = gradient; ctx.fillRect(0, 0, width, height)
  if (frame.flashOpacity > 0) { ctx.save(); ctx.globalAlpha = frame.flashOpacity; ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, width, height); ctx.restore() }
  if (slide.showText) { const positionRatio = slide.textPosition === 'upper' ? format.safeTop + .18 : slide.textPosition === 'center' ? .54 : 1 - format.safeBottom - .06; ctx.save(); ctx.globalAlpha = frame.textOpacity; const baseline = height * positionRatio; ctx.translate(width / 2, baseline + frame.textTranslateY * height / 430); ctx.scale(frame.textScale, frame.textScale); ctx.textAlign = 'center'; ctx.shadowColor = 'rgba(0,0,0,.8)'; ctx.shadowBlur = width * .018; ctx.fillStyle = '#fff'; ctx.font = `700 ${Math.round(width * .073)}px system-ui, sans-serif`; ctx.fillText(title || 'My story', 0, 0, width * .82); if (cta) { ctx.fillStyle = pattern.accent; ctx.font = `600 ${Math.round(width * .03)}px system-ui, sans-serif`; ctx.fillText(cta, 0, height * .07, width * .72) } ctx.restore() }
}

export default function App() {
  const [language, setLanguage] = useState<Language>(() => getInitialLanguage(localStorage.getItem('language'))); const t = (key: Parameters<typeof translate>[1]) => translate(language, key)
  const [slides, setSlides] = useState<Slide[]>([]); const [title, setTitle] = useState(() => translate(getInitialLanguage(localStorage.getItem('language')), 'defaultTitleValue')); const [cta, setCta] = useState(() => translate(getInitialLanguage(localStorage.getItem('language')), 'defaultCtaValue')); const [seconds, setSeconds] = useState(3)
  const [patternId, setPatternId] = useState<VideoPatternId>(() => isVideoPatternId(localStorage.getItem('videoPattern')) ? localStorage.getItem('videoPattern') as VideoPatternId : 'cinematic')
  const [formatId, setFormatId] = useState<VideoFormatId>(() => isVideoFormatId(localStorage.getItem('videoFormat')) ? localStorage.getItem('videoFormat') as VideoFormatId : 'reel')
  const [qualityId, setQualityId] = useState<VideoQualityId>(() => isVideoQualityId(localStorage.getItem('videoQuality')) ? localStorage.getItem('videoQuality') as VideoQualityId : 'high')
  const [playing, setPlaying] = useState(false); const [time, setTime] = useState(0); const [exporting, setExporting] = useState(false); const [loadingImages, setLoadingImages] = useState(false); const [notice, setNotice] = useState(''); const [aiNotice, setAiNotice] = useState('')
  const [aiEnabled, setAiEnabled] = useState(false); const [aiProvider, setAiProvider] = useState<AiProviderId>(() => (localStorage.getItem('aiProvider') as AiProviderId) || 'chrome'); const [chromeAiStatus, setChromeAiStatus] = useState<ChromeAiAvailability | null>(null)
  const [ollamaUrl, setOllamaUrl] = useState(() => initialOllamaUrl(localStorage.getItem('ollamaLocalUrl'))); const [ollamaModel, setOllamaModel] = useState(() => localStorage.getItem('ollamaModel') || 'gemma3:4b'); const [ollamaModels, setOllamaModels] = useState<OllamaModel[]>([])
  const [copyPreset, setCopyPreset] = useState<'auto' | 'engagement' | 'storytelling' | 'product'>('auto'); const [customDirection, setCustomDirection] = useState(''); const [aiLoading, setAiLoading] = useState(false)
  const slidesRef = useRef<Slide[]>([]); const raf = useRef(0); const startedAt = useRef(0); const inputRef = useRef<HTMLInputElement>(null)
  const durationFloor = minSecondsPerImage(slides.length)
  const total = slides.length * seconds; const frame = getFrameState(time, slides.length, seconds); const pattern = getVideoPattern(patternId); const format = getVideoFormat(formatId); const quality = getVideoQuality(qualityId); const patternFrame = getPatternFrame(patternId, frame.progress, frame.index)
  const patternName = pattern.name[language]; const formatName = format.name[language]; const qualityName = quality.name[language]
  const copyDirections = language === 'en' ? { auto: pattern.copyDirection.en, engagement: 'Invite saves, comments, or shares naturally. Lead with a strong hook.', storytelling: 'Turn the scene into a concise story that makes viewers want to continue.', product: 'Explain the value and outcome clearly without sounding pushy.' } : { auto: pattern.copyDirection.ja, engagement: '保存・コメント・シェアを自然に促す。冒頭で興味を引く', storytelling: '情景と体験を物語として伝え、続きを見たくさせる', product: '商品の価値と利用後の変化を具体的かつ簡潔に伝える' }
  useEffect(() => { slidesRef.current = slides }, [slides]); useEffect(() => () => slidesRef.current.forEach(slide => URL.revokeObjectURL(slide.url)), [])
  useEffect(() => { setSeconds(current => Math.max(current, durationFloor)) }, [durationFloor])
  useEffect(() => { if (!playing || !total) return; startedAt.current = performance.now() - time * 1000; const tick = (now: number) => { const next = (now - startedAt.current) / 1000; if (next >= total) { setTime(0); setPlaying(false); return } setTime(next); raf.current = requestAnimationFrame(tick) }; raf.current = requestAnimationFrame(tick); return () => cancelAnimationFrame(raf.current) }, [playing, total])
  const addImages = async (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []).filter(file => file.type.startsWith('image/') || isHeicFile(file)); if (!files.length) return; setLoadingImages(true); setNotice(''); try { const loaded = await Promise.all(files.map(async file => { const blob = await normalizeImageFile(file); return new Promise<Slide>((resolve, reject) => { const url = URL.createObjectURL(blob); const image = new Image(); image.onload = () => resolve({ id: crypto.randomUUID(), name: file.name, url, image, blob, title: '', cta: '', showText: false, textPosition: 'lower' }); image.onerror = () => { URL.revokeObjectURL(url); reject(new Error(`${file.name}: ${t('imageReadError')}`)) }; image.src = url }) })); setSlides(current => [...current, ...loaded]) } catch (error) { setNotice(error instanceof Error ? error.message : t('imageConvertError')) } finally { setLoadingImages(false); event.target.value = '' } }
  const remove = (index: number) => setSlides(current => { URL.revokeObjectURL(current[index].url); return current.filter((_, i) => i !== index) })
  const updateSlide = (index: number, patch: Partial<Pick<Slide, 'title' | 'cta' | 'showText' | 'textPosition'>>) => setSlides(current => current.map((slide, i) => i === index ? { ...slide, ...patch } : slide))
  const clearSlideCopy = (index: number) => updateSlide(index, { title: '', cta: '', showText: false })
  const changeLanguage = (next: Language) => { setLanguage(next); localStorage.setItem('language', next) }
  const checkChromeAi = async () => { setAiNotice(t('chromeChecking')); try { const status = await prepareChromeAi({ language, onDownloadProgress: progress => setAiNotice(`${t('chromePreparing')} ${progress}%`) }); setChromeAiStatus(status); setAiNotice(chromeAiAvailabilityMessage(status, language)) } catch (error) { setAiNotice(error instanceof Error ? error.message : t('chromePrepareError')) } }
  const checkOllama = async () => { setAiNotice(t('connectionChecking')); try { const result = aiProvider === 'ollama-local' ? await discoverLocalOllama(ollamaUrl, language) : { url: ollamaUrl, models: await listOllamaModels(ollamaUrl, aiProvider, undefined, language) }; setOllamaUrl(result.url); setOllamaModels(result.models); const selected = selectVisionModel(result.models, ollamaModel); setOllamaModel(selected); localStorage.setItem('ollamaLocalUrl', result.url); localStorage.setItem('ollamaModel', selected); const vision = result.models.filter(supportsVision); if (!result.models.length) setAiNotice(`${t('connectionSuccess')} · ${t('noModels')}`); else setAiNotice(`${t('connectionSuccess')} · ${result.url} · ${result.models.length} ${t('installedModels')} · ${vision.length ? `${t('visionReady')}: ${selected}` : t('visionUnknown')}`) } catch (error) { setOllamaModels([]); setAiNotice(`${t('notRunning')} ${error instanceof Error ? error.message : ''}`.trim()) } }
  const askAi = async () => { const targets = slides.filter(slide => slide.showText); if (!targets.length) { setAiNotice(t('aiNoSelection')); return } setAiLoading(true); setAiNotice(t('aiWorking')); localStorage.setItem('aiProvider', aiProvider); try { const direction = copyDirections[copyPreset]; const copies = new Map<string, AiCopy>(); for (const slide of targets) copies.set(slide.id, aiProvider === 'chrome' ? await generateChromeAiCopy({ image: slide.blob, direction, customDirection, formatName, language, onDownloadProgress: progress => setAiNotice(`${t('chromePreparing')} ${progress}%`) }) : await generateAiCopy({ baseUrl: ollamaUrl, provider: aiProvider, model: ollamaModel, image: slide.blob, direction, customDirection, formatName, language })); setSlides(current => current.map(slide => { const copy = copies.get(slide.id); return copy ? { ...slide, title: copy.title, cta: copy.cta, showText: true } : slide })); setAiNotice(t('aiApplied')) } catch (error) { setAiNotice(error instanceof Error ? error.message : t('aiError')) } finally { setAiLoading(false) } }
  const exportVideo = async () => { if (!slides.length) return; setExporting(true); try { const canvas = document.createElement('canvas'); canvas.width = format.width * quality.scale; canvas.height = format.height * quality.scale; const draw = (ctx: CanvasRenderingContext2D, elapsed: number) => { const state = getFrameState(elapsed, slides.length, seconds); drawFrame(ctx, slides[state.index], state.progress, slides[state.index].title || title, slides[state.index].cta || cta, patternId, formatId, state.index) }; let lastPreview = -1; const onProgress = (elapsed: number) => { if (elapsed - lastPreview >= .1) { setTime(elapsed); lastPreview = elapsed } }; const codec = await pickVideoCodec(canvas.width, canvas.height, quality.bitsPerSecond); const result = codec ? { blob: await renderMp4({ canvas, fps: quality.fps, bitrate: quality.bitsPerSecond, durationSeconds: total, codec, draw, onProgress }), extension: 'mp4' } : 'MediaRecorder' in window ? { blob: await renderWebm({ canvas, fps: quality.fps, bitrate: quality.bitsPerSecond, durationSeconds: total, draw, onProgress }), extension: 'webm' } : null; if (!result) return; const url = URL.createObjectURL(result.blob); const link = document.createElement('a'); link.href = url; link.download = `${format.fileName}.${result.extension}`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 2000); setTime(0) } finally { setExporting(false) } }
  const styleVars = { '--pattern-accent': pattern.accent, '--preview-ratio': `${format.width}/${format.height}`, '--safe-top': `${format.safeTop * 100}%`, '--safe-bottom': `${format.safeBottom * 100}%` } as CSSProperties
  return <div className="app-shell"><header><div className="brand"><span className="brand-mark">F</span><span>Frameflow</span></div><div className="header-actions"><span className="eyebrow">MULTI-FORMAT VIDEO STUDIO</span><div className="language-switch" role="group" aria-label={t('language')}><span>{t('language')}</span><button className={language==='en'?'active':''} aria-pressed={language==='en'} onClick={()=>changeLanguage('en')}>EN</button><button className={language==='ja'?'active':''} aria-pressed={language==='ja'} onClick={()=>changeLanguage('ja')}>日本語</button></div></div></header><main><section className="intro"><p className="kicker">IMAGES TO MOTION</p><h1>{language==='en'?<>Turn photos into <em>moving stories.</em></>:<>写真から、<em>動く物語</em>を。</>}</h1><p>{language==='en'?'Create polished Reels, Stories, posts and Shorts with format-aware high-quality settings.':'リール、ストーリー、フィード、Shortsを用途別の高品質設定で仕上げます。'}</p></section><div className="workspace"><section className="editor panel">
    <div className="section-head"><div><span>01</span><h2>{t('buildStory')}</h2></div><button className="add-small" onClick={() => inputRef.current?.click()}>＋ {t('addImages')}</button></div><input ref={inputRef} type="file" accept="image/*,.heic,.heif" multiple hidden onChange={addImages}/>{notice && <p className="notice" role="alert">{notice}</p>}
    {slides.length === 0 ? <button className="dropzone" disabled={loadingImages} onClick={() => inputRef.current?.click()}><span className="upload-icon">↗</span><strong>{loadingImages ? t('converting') : t('selectPhotos')}</strong><small>JPG / PNG / WEBP / HEIC / HEIF</small></button> : <div className="story-list">{slides.map((slide,index)=><article className="story-item" key={slide.id}><img src={slide.url} alt=""/><div className="story-meta"><b>{String(index+1).padStart(2,'0')}</b><span>{slide.name}</span></div><div className="item-actions"><button disabled={index===0} onClick={()=>setSlides(moveItem(slides,index,index-1))}>↑</button><button disabled={index===slides.length-1} onClick={()=>setSlides(moveItem(slides,index,index+1))}>↓</button><button onClick={()=>remove(index)}>×</button></div></article>)}</div>}
    <section className="format-section"><div className="pattern-head"><div><span>▣</span><div><h3>{t('formatTitle')}</h3><p>{t('optimizeSafeArea')}</p></div></div><strong>{format.width} × {format.height}</strong></div><div className="format-grid">{VIDEO_FORMATS.map(item=><button key={item.id} className={formatId===item.id?'active':''} aria-pressed={formatId===item.id} onClick={()=>{setFormatId(item.id);localStorage.setItem('videoFormat',item.id)}}><b>{item.name[language]}</b><small>{item.description[language]}</small></button>)}</div><div className="quality-row">{VIDEO_QUALITIES.map(item=><button key={item.id} className={qualityId===item.id?'active':''} aria-pressed={qualityId===item.id} onClick={()=>{setQualityId(item.id);localStorage.setItem('videoQuality',item.id)}}><b>{item.name[language]}</b><small>{item.description[language]}</small></button>)}</div></section>
    <div className="fields"><label>{t('defaultTitle')}<input value={title} maxLength={28} onChange={e=>setTitle(e.target.value)}/></label><label>{t('defaultCta')}<input value={cta} maxLength={32} onChange={e=>setCta(e.target.value)}/></label><small className="field-help">{t('commonFallback')}</small><label>{t('duration')}<div className="range-row"><input type="range" min={durationFloor} max="6" value={seconds} onChange={e=>setSeconds(Number(e.target.value))}/><output>{seconds}{t('seconds')}</output></div></label><small className="field-help">{t('durationFloorHint')}</small></div>
    {slides.length>0&&<section className="slide-copy-section"><div className="pattern-head"><div><span>✎</span><div><h3>{t('slideCopy')} <strong className="copy-count">{slides.length}</strong></h3><p>{t('perSlideHint')}</p></div></div></div><div className="slide-copy-list">{slides.map((slide,index)=><article className="slide-copy-card" key={`copy-${slide.id}`}><div className="slide-copy-heading"><div className="copy-identity"><img src={slide.url} alt=""/><div><b>{String(index+1).padStart(2,'0')} · {slide.name}</b><small>{slide.title||slide.cta?t('showText'):t('copyEmpty')}</small></div></div><div className="copy-actions"><label className="inline-toggle"><input type="checkbox" checked={slide.showText} onChange={e=>updateSlide(index,{showText:e.target.checked})}/>{t('showText')}</label><button className="clear-copy" title={t('clearConfirm')} onClick={()=>clearSlideCopy(index)}>{t('clearCopy')}</button></div></div><div className="slide-copy-grid"><label>{t('defaultTitle')}<input value={slide.title} maxLength={28} placeholder={t('copyEmpty')} onChange={e=>updateSlide(index,{title:e.target.value,showText:Boolean(e.target.value||slide.cta)})}/></label><label>{t('defaultCta')}<input value={slide.cta} maxLength={32} placeholder={t('copyEmpty')} onChange={e=>updateSlide(index,{cta:e.target.value,showText:Boolean(slide.title||e.target.value)})}/></label><label>{t('textPosition')}<select value={slide.textPosition} onChange={e=>updateSlide(index,{textPosition:e.target.value as TextPosition})}><option value="lower">{t('lower')}</option><option value="center">{t('center')}</option><option value="upper">{t('upper')}</option></select></label></div></article>)}</div></section>}
    <section className="pattern-section"><div className="pattern-head"><div><span>✦</span><div><h3>{t('motionTitle')}</h3><p>{t('patternDescription')}</p></div></div><strong>{patternName}</strong></div><div className="pattern-grid">{VIDEO_PATTERNS.map(item=><button key={item.id} className={patternId===item.id?'active':''} aria-pressed={patternId===item.id} style={{'--pattern-accent':item.accent} as CSSProperties} onClick={()=>{setPatternId(item.id);localStorage.setItem('videoPattern',item.id);setPlaying(false)}}><span className="pattern-preview"><i/><i/><i/></span><b>{item.name[language]}</b><small>{item.description[language]}</small></button>)}</div></section>
    <section className="ai-card"><div className="ai-card-head"><div><span className="ai-spark">✦</span><div><h3>{t('aiCopy')}</h3><p>{t('aiCopyDescription')}</p></div></div><button className={`toggle ${aiEnabled?'on':''}`} aria-pressed={aiEnabled} onClick={()=>setAiEnabled(!aiEnabled)}><span/></button></div>{aiEnabled&&<div className="ai-fields"><div className="provider-tabs three"><button className={aiProvider==='chrome'?'active':''} onClick={()=>setAiProvider('chrome')}>{t('chromeProvider')}</button><button className={aiProvider==='ollama-local'?'active':''} onClick={()=>setAiProvider('ollama-local')}>{t('localOllama')}</button><button className={aiProvider==='ollama-cloud'?'active':''} onClick={()=>setAiProvider('ollama-cloud')}>{t('ollamaCloud')}</button></div>
      {aiProvider==='chrome'?<><button className="ai-check" onClick={checkChromeAi}>{t('checkChrome')}</button>{chromeAiStatus&&<small className="ai-status">{chromeAiAvailabilityMessage(chromeAiStatus, language)}</small>}<small>{t('chromeHint')}</small></>:<><div className="ai-grid">{aiProvider==='ollama-local'&&<label>{t('localEndpoint')}<input value={ollamaUrl} onChange={e=>setOllamaUrl(e.target.value)}/></label>}<label>{t('visionModel')}<input list="ollama-models" value={ollamaModel} onChange={e=>setOllamaModel(e.target.value)}/><datalist id="ollama-models">{ollamaModels.map(model=><option key={model.name} value={model.name}>{supportsVision(model)?t('visionReady'):t('visionUnknown')}</option>)}{RECOMMENDED_VISION_MODELS.map(model=><option key={model.name} value={model.name}>{model.note[language]}</option>)}</datalist></label></div><button className="ai-check" onClick={checkOllama}>{aiProvider==='ollama-local'?t('detectOllama'):t('fetchModels')}</button><small>{aiProvider==='ollama-cloud'?t('cloudHint'):t('ollamaHint')}</small>{aiProvider==='ollama-local'&&<><div className="ollama-result"><b>{t('connectedEndpoint')}</b><code>{ollamaUrl}</code><b>{t('installedModels')} ({ollamaModels.length})</b>{ollamaModels.length?<ul>{ollamaModels.map(model=><li key={model.name}><code>{model.name}</code><span className={supportsVision(model)?'vision-ok':'vision-unknown'}>{supportsVision(model)?t('visionReady'):t('visionUnknown')}</span></li>)}</ul>:<small>{t('noModels')}</small>}</div><details className="ollama-help" open={!ollamaModels.length}><summary>{t('ollamaHelpTitle')}</summary><p>{t('ollamaBrowserLimit')}</p><ol><li>{t('ollamaHelp1')}</li><li>{t('ollamaHelp2')}</li><li>{t('ollamaHelp3')}</li><li>{t('ollamaHelp4')}</li></ol><code>OLLAMA_ORIGINS="http://localhost:5173,http://127.0.0.1:5173" ollama serve</code></details></>}</>}{aiNotice&&<p className="ai-notice" role="status">{aiNotice}</p>}
      <small className="per-slide-note">{t('aiSelectHint')}</small><label>{t('copyDirection')}<select value={copyPreset} onChange={e=>setCopyPreset(e.target.value as typeof copyPreset)}><option value="auto">{t('auto')}</option><option value="engagement">{t('engagement')}</option><option value="storytelling">{t('storytelling')}</option><option value="product">{t('product')}</option></select><small className="direction-preview">{copyDirections[copyPreset]}</small></label><label>{t('customRequest')}<textarea rows={3} value={customDirection} onChange={e=>setCustomDirection(e.target.value)}/></label><button className="ai-generate" disabled={!slides.length||aiLoading||(aiProvider!=='chrome'&&!ollamaModel.trim())} onClick={askAi}>{aiLoading?t('generating'):`✦ ${t('generateCopy')}`}</button></div>}</section>
  </section><section className="preview-side"><div className="section-head preview-title"><div><span>02</span><h2>{t('preview')}</h2></div><small>{formatName} · {qualityName}</small></div><div className={`phone pattern-${patternId}`} style={styleVars}><div className="phone-screen">{slides.length?<><img className="hero-image" src={slides[frame.index]?.url} alt={t('previewAlt')} style={{transform:patternTransform(patternFrame),opacity:patternFrame.imageOpacity,filter:pattern.filter}}/><div className="scrim" style={{opacity:patternFrame.overlayOpacity}}/>{pattern.decoration==='letterbox'&&<><div className="letterbox-bar top"/><div className="letterbox-bar bottom"/></>}{(pattern.decoration==='vignette'||pattern.decoration==='frame')&&<div className={`vignette-overlay ${pattern.decoration}`}/>}{patternFrame.flashOpacity>0&&<div className="flash-overlay" style={{opacity:patternFrame.flashOpacity}}/>}{pattern.decoration==='badge'&&<div className="accent-badge" style={{transform:`scale(${patternFrame.textScale})`}}>✦</div>}<div className="safe-guide"/>{slides[frame.index]?.showText&&<div className={`reel-copy position-${slides[frame.index]?.textPosition}`} style={{opacity:patternFrame.textOpacity,transform:`translateY(${patternFrame.textTranslateY}px) scale(${patternFrame.textScale})`}}><h3>{slides[frame.index]?.title||title||'My story'}</h3>{(slides[frame.index]?.cta||cta)&&<p>{slides[frame.index]?.cta||cta}</p>}</div>}<div className="counter">{frame.index+1} / {slides.length}</div><div className="pattern-badge">{patternName}</div></>:<div className="empty-preview"><span>✦</span><p>{t('emptyPreviewLong')}</p></div>}</div></div><div className="transport"><button className="play" disabled={!slides.length} onClick={()=>setPlaying(!playing)}>{playing?'Ⅱ':'▶'}</button><input type="range" min="0" max={total||1} step=".01" value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value))}}/><time>{Math.floor(time)}s / {total}s</time></div><button className="export" disabled={!slides.length||exporting} onClick={exportVideo}>{exporting?t('exporting'):t('exportVideo')}<span>MP4 · {format.width} × {format.height} · {quality.fps}fps</span></button></section></div></main><footer><span>FRAMEFLOW / MULTI-FORMAT EDITION</span><span>{t('privacy')}</span></footer></div>
}
