import { useEffect, useRef, useState } from 'react'
import type { ChangeEvent, CSSProperties } from 'react'
import { generateAiCopy, initialOllamaUrl, isHeicFile, listOllamaModels, RECOMMENDED_VISION_MODELS, supportsVision } from './ai'
import type { AiProviderId, OllamaModel } from './ai'
import { chromeAiAvailabilityMessage, generateChromeAiCopy, getChromeAiAvailability } from './chrome-ai'
import type { ChromeAiAvailability } from './chrome-ai'
import { normalizeImageFile } from './image'
import { VIDEO_FORMATS, VIDEO_PATTERNS, VIDEO_QUALITIES, getFrameState, getMimeType, getPatternFrame, getVideoFormat, getVideoPattern, getVideoQuality, isVideoFormatId, isVideoPatternId, isVideoQualityId, moveItem } from './reel'
import type { PatternFrame, VideoFormatId, VideoPatternId, VideoQualityId } from './reel'

type Slide = { id: string; name: string; url: string; image: HTMLImageElement; blob: Blob }
const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))
function cover(ctx: CanvasRenderingContext2D, image: HTMLImageElement, width: number, height: number, scale = 1) { const ratio = Math.max(width / image.naturalWidth, height / image.naturalHeight) * scale; const w = image.naturalWidth * ratio; const h = image.naturalHeight * ratio; ctx.drawImage(image, (width - w) / 2, (height - h) / 2, w, h) }
function patternTransform(frame: PatternFrame) { return `translate(${frame.translateX}%, ${frame.translateY}%) rotate(${frame.rotation}deg) scale(${frame.scale})` }
function drawFrame(ctx: CanvasRenderingContext2D, slide: Slide, progress: number, title: string, cta: string, patternId: VideoPatternId, formatId: VideoFormatId, index: number) {
  const { width, height } = ctx.canvas; const frame = getPatternFrame(patternId, progress, index); const pattern = getVideoPattern(patternId); const format = getVideoFormat(formatId)
  ctx.fillStyle = '#09080d'; ctx.fillRect(0, 0, width, height); ctx.save(); ctx.globalAlpha = frame.imageOpacity; ctx.translate(width / 2 + width * frame.translateX / 100, height / 2 + height * frame.translateY / 100); ctx.rotate(frame.rotation * Math.PI / 180); ctx.translate(-width / 2, -height / 2); cover(ctx, slide.image, width, height, frame.scale); ctx.restore()
  const gradient = ctx.createLinearGradient(0, height * .36, 0, height); gradient.addColorStop(0, 'rgba(8,7,13,0)'); gradient.addColorStop(1, `rgba(8,7,13,${frame.overlayOpacity})`); ctx.fillStyle = gradient; ctx.fillRect(0, 0, width, height)
  ctx.save(); ctx.globalAlpha = frame.textOpacity; const baseline = height * (1 - format.safeBottom - .06); ctx.translate(width / 2, baseline + frame.textTranslateY * height / 430); ctx.scale(frame.textScale, frame.textScale); ctx.textAlign = 'center'; ctx.fillStyle = '#fff'; ctx.font = `700 ${Math.round(width * .073)}px system-ui, sans-serif`; ctx.fillText(title || 'My story', 0, 0, width * .82); if (cta) { ctx.fillStyle = pattern.accent; ctx.font = `600 ${Math.round(width * .03)}px system-ui, sans-serif`; ctx.fillText(cta, 0, height * .07, width * .72) } ctx.restore()
}

export default function App() {
  const [slides, setSlides] = useState<Slide[]>([]); const [title, setTitle] = useState('週末の小さな旅'); const [cta, setCta] = useState('保存して、次の休日へ'); const [seconds, setSeconds] = useState(3)
  const [patternId, setPatternId] = useState<VideoPatternId>(() => isVideoPatternId(localStorage.getItem('videoPattern')) ? localStorage.getItem('videoPattern') as VideoPatternId : 'cinematic')
  const [formatId, setFormatId] = useState<VideoFormatId>(() => isVideoFormatId(localStorage.getItem('videoFormat')) ? localStorage.getItem('videoFormat') as VideoFormatId : 'reel')
  const [qualityId, setQualityId] = useState<VideoQualityId>(() => isVideoQualityId(localStorage.getItem('videoQuality')) ? localStorage.getItem('videoQuality') as VideoQualityId : 'high')
  const [playing, setPlaying] = useState(false); const [time, setTime] = useState(0); const [exporting, setExporting] = useState(false); const [loadingImages, setLoadingImages] = useState(false); const [notice, setNotice] = useState('')
  const [aiEnabled, setAiEnabled] = useState(false); const [aiProvider, setAiProvider] = useState<AiProviderId>(() => (localStorage.getItem('aiProvider') as AiProviderId) || 'chrome'); const [chromeAiStatus, setChromeAiStatus] = useState<ChromeAiAvailability | null>(null)
  const [ollamaUrl, setOllamaUrl] = useState(() => initialOllamaUrl(localStorage.getItem('ollamaLocalUrl'))); const [ollamaModel, setOllamaModel] = useState(() => localStorage.getItem('ollamaModel') || 'gemma3:4b'); const [ollamaModels, setOllamaModels] = useState<OllamaModel[]>([])
  const [copyPreset, setCopyPreset] = useState<'auto' | 'engagement' | 'storytelling' | 'product'>('auto'); const [customDirection, setCustomDirection] = useState(''); const [aiLoading, setAiLoading] = useState(false)
  const slidesRef = useRef<Slide[]>([]); const raf = useRef(0); const startedAt = useRef(0); const inputRef = useRef<HTMLInputElement>(null)
  const total = slides.length * seconds; const frame = getFrameState(time, slides.length, seconds); const pattern = getVideoPattern(patternId); const format = getVideoFormat(formatId); const quality = getVideoQuality(qualityId); const patternFrame = getPatternFrame(patternId, frame.progress, frame.index)
  const copyDirections = { auto: pattern.copyDirection, engagement: '保存・コメント・シェアを自然に促す。冒頭で興味を引く', storytelling: '情景と体験を物語として伝え、続きを見たくさせる', product: '商品の価値と利用後の変化を具体的かつ簡潔に伝える' }
  useEffect(() => { slidesRef.current = slides }, [slides]); useEffect(() => () => slidesRef.current.forEach(slide => URL.revokeObjectURL(slide.url)), [])
  useEffect(() => { if (!playing || !total) return; startedAt.current = performance.now() - time * 1000; const tick = (now: number) => { const next = (now - startedAt.current) / 1000; if (next >= total) { setTime(0); setPlaying(false); return } setTime(next); raf.current = requestAnimationFrame(tick) }; raf.current = requestAnimationFrame(tick); return () => cancelAnimationFrame(raf.current) }, [playing, total])
  const addImages = async (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []).filter(file => file.type.startsWith('image/') || isHeicFile(file)); if (!files.length) return; setLoadingImages(true); setNotice(''); try { const loaded = await Promise.all(files.map(async file => { const blob = await normalizeImageFile(file); return new Promise<Slide>((resolve, reject) => { const url = URL.createObjectURL(blob); const image = new Image(); image.onload = () => resolve({ id: crypto.randomUUID(), name: file.name, url, image, blob }); image.onerror = () => { URL.revokeObjectURL(url); reject(new Error(`${file.name}を読み込めませんでした。`)) }; image.src = url }) })); setSlides(current => [...current, ...loaded]) } catch (error) { setNotice(error instanceof Error ? error.message : '画像の変換に失敗しました。') } finally { setLoadingImages(false); event.target.value = '' } }
  const remove = (index: number) => setSlides(current => { URL.revokeObjectURL(current[index].url); return current.filter((_, i) => i !== index) })
  const checkChromeAi = async () => { setNotice('Chrome AIの利用状況を確認しています…'); const status = await getChromeAiAvailability(); setChromeAiStatus(status); setNotice(chromeAiAvailabilityMessage(status)) }
  const checkOllama = async () => { setNotice(`${aiProvider === 'ollama-cloud' ? 'Ollama Cloud' : 'ローカルOllama'}へ接続しています…`); try { const models = await listOllamaModels(ollamaUrl, aiProvider); setOllamaModels(models); const vision = models.filter(supportsVision); if (!models.length) setNotice('モデルが見つかりません。接続設定とアカウントの利用可能モデルを確認してください。'); else setNotice(`接続成功。画像対応モデル: ${vision.map(m => m.name).join(', ') || '検出なし'}`) } catch (error) { setNotice(error instanceof Error ? error.message : 'Ollamaへ接続できませんでした。') } }
  const askAi = async () => { if (!slides.length) return; setAiLoading(true); setNotice(''); localStorage.setItem('aiProvider', aiProvider); try { const direction = copyDirections[copyPreset]; const copy = aiProvider === 'chrome' ? await generateChromeAiCopy({ image: slides[0].blob, direction, customDirection, formatName: format.name, onDownloadProgress: progress => setNotice(`Chrome AIモデルを準備中… ${progress}%`) }) : await generateAiCopy({ baseUrl: ollamaUrl, provider: aiProvider, model: ollamaModel, image: slides[0].blob, direction, customDirection, formatName: format.name }); setTitle(copy.title); setCta(copy.cta); setNotice(`${aiProvider === 'chrome' ? 'Chrome AI' : aiProvider === 'ollama-cloud' ? 'Ollama Cloud' : 'ローカルOllama'}の提案を反映しました。`) } catch (error) { setNotice(error instanceof Error ? error.message : 'AIモードでエラーが発生しました。') } finally { setAiLoading(false) } }
  const exportVideo = async () => { if (!slides.length || !('MediaRecorder' in window)) return; setExporting(true); try { const canvas = document.createElement('canvas'); canvas.width = format.width * quality.scale; canvas.height = format.height * quality.scale; const ctx = canvas.getContext('2d')!; const stream = canvas.captureStream(quality.fps); const mimeType = getMimeType(MediaRecorder.isTypeSupported); const recorder = new MediaRecorder(stream, { mimeType, videoBitsPerSecond: quality.bitsPerSecond }); const chunks: Blob[] = []; recorder.ondataavailable = event => event.data.size && chunks.push(event.data); const done = new Promise<void>(resolve => recorder.onstop = () => resolve()); recorder.start(250); const start = performance.now(); while (true) { const elapsed = (performance.now() - start) / 1000; if (elapsed >= total) break; const state = getFrameState(elapsed, slides.length, seconds); drawFrame(ctx, slides[state.index], state.progress, title, cta, patternId, formatId, state.index); setTime(elapsed); await sleep(1000 / quality.fps) } recorder.stop(); await done; const url = URL.createObjectURL(new Blob(chunks, { type: mimeType })); const link = document.createElement('a'); link.href = url; link.download = `${format.fileName}.webm`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 2000); setTime(0) } finally { setExporting(false) } }
  const styleVars = { '--pattern-accent': pattern.accent, '--preview-ratio': `${format.width}/${format.height}`, '--safe-top': `${format.safeTop * 100}%`, '--safe-bottom': `${format.safeBottom * 100}%` } as CSSProperties
  return <div className="app-shell"><header><div className="brand"><span className="brand-mark">F</span><span>Frameflow</span></div><span className="eyebrow">MULTI-FORMAT VIDEO STUDIO</span></header><main><section className="intro"><p className="kicker">IMAGES TO MOTION</p><h1>写真から、<em>動く物語</em>を。</h1><p>リール、ストーリー、フィード、Shortsを用途別の高品質設定で仕上げます。</p></section><div className="workspace"><section className="editor panel">
    <div className="section-head"><div><span>01</span><h2>ストーリーを組み立てる</h2></div><button className="add-small" onClick={() => inputRef.current?.click()}>＋ 画像を追加</button></div><input ref={inputRef} type="file" accept="image/*,.heic,.heif" multiple hidden onChange={addImages}/>{notice && <p className="notice" role="alert">{notice}</p>}
    {slides.length === 0 ? <button className="dropzone" disabled={loadingImages} onClick={() => inputRef.current?.click()}><span className="upload-icon">↗</span><strong>{loadingImages ? '画像を変換中…' : '写真を選択'}</strong><small>JPG / PNG / WEBP / HEIC / HEIF</small></button> : <div className="story-list">{slides.map((slide,index)=><article className="story-item" key={slide.id}><img src={slide.url} alt=""/><div className="story-meta"><b>{String(index+1).padStart(2,'0')}</b><span>{slide.name}</span></div><div className="item-actions"><button disabled={index===0} onClick={()=>setSlides(moveItem(slides,index,index-1))}>↑</button><button disabled={index===slides.length-1} onClick={()=>setSlides(moveItem(slides,index,index+1))}>↓</button><button onClick={()=>remove(index)}>×</button></div></article>)}</div>}
    <section className="format-section"><div className="pattern-head"><div><span>▣</span><div><h3>動画の用途</h3><p>比率と安全領域を最適化</p></div></div><strong>{format.width} × {format.height}</strong></div><div className="format-grid">{VIDEO_FORMATS.map(item=><button key={item.id} className={formatId===item.id?'active':''} aria-pressed={formatId===item.id} onClick={()=>{setFormatId(item.id);localStorage.setItem('videoFormat',item.id)}}><b>{item.name}</b><small>{item.description}</small></button>)}</div><div className="quality-row">{VIDEO_QUALITIES.map(item=><button key={item.id} className={qualityId===item.id?'active':''} aria-pressed={qualityId===item.id} onClick={()=>{setQualityId(item.id);localStorage.setItem('videoQuality',item.id)}}><b>{item.name}</b><small>{item.description}</small></button>)}</div></section>
    <div className="fields"><label>タイトル<input value={title} maxLength={28} onChange={e=>setTitle(e.target.value)}/></label><label>CTA<input value={cta} maxLength={32} onChange={e=>setCta(e.target.value)}/></label><label>1枚の表示時間<div className="range-row"><input type="range" min="2" max="6" value={seconds} onChange={e=>setSeconds(Number(e.target.value))}/><output>{seconds}秒</output></div></label></div>
    <section className="pattern-section"><div className="pattern-head"><div><span>✦</span><div><h3>動画パターン</h3><p>演出とコピー方向性を連動</p></div></div><strong>{pattern.name}</strong></div><div className="pattern-grid">{VIDEO_PATTERNS.map(item=><button key={item.id} className={patternId===item.id?'active':''} aria-pressed={patternId===item.id} style={{'--pattern-accent':item.accent} as CSSProperties} onClick={()=>{setPatternId(item.id);localStorage.setItem('videoPattern',item.id);setPlaying(false)}}><span className="pattern-preview"><i/><i/><i/></span><b>{item.name}</b><small>{item.description}</small></button>)}</div></section>
    <section className="ai-card"><div className="ai-card-head"><div><span className="ai-spark">✦</span><div><h3>AIコピー提案</h3><p>動画用途と演出に合わせて提案</p></div></div><button className={`toggle ${aiEnabled?'on':''}`} aria-pressed={aiEnabled} onClick={()=>setAiEnabled(!aiEnabled)}><span/></button></div>{aiEnabled&&<div className="ai-fields"><div className="provider-tabs three"><button className={aiProvider==='chrome'?'active':''} onClick={()=>setAiProvider('chrome')}>Chrome端末内AI</button><button className={aiProvider==='ollama-local'?'active':''} onClick={()=>setAiProvider('ollama-local')}>ローカルOllama</button><button className={aiProvider==='ollama-cloud'?'active':''} onClick={()=>setAiProvider('ollama-cloud')}>Ollama Cloud</button></div>
      {aiProvider==='chrome'?<><button className="ai-check" onClick={checkChromeAi}>利用状況を確認</button>{chromeAiStatus&&<small className="ai-status">{chromeAiAvailabilityMessage(chromeAiStatus)}</small>}<small>対応Chrome内でのみ動作します。サーバー裏側では実行できません。</small></>:<><div className="ai-grid">{aiProvider==='ollama-local'&&<label>ローカル接続先<input value={ollamaUrl} onChange={e=>setOllamaUrl(e.target.value)}/></label>}<label>画像対応モデル<input list="ollama-models" value={ollamaModel} onChange={e=>setOllamaModel(e.target.value)}/><datalist id="ollama-models">{ollamaModels.map(model=><option key={model.name} value={model.name}>{supportsVision(model)?'画像対応':'対応未確認'}</option>)}{RECOMMENDED_VISION_MODELS.map(model=><option key={model.name} value={model.name}>{model.note}</option>)}</datalist></label></div><button className="ai-check" onClick={checkOllama}>接続してモデル一覧を取得</button><small>{aiProvider==='ollama-cloud'?'サーバー環境変数 OLLAMA_CLOUD_API_KEY を使用します。利用料金・無料枠はOllamaアカウント側で確認してください。':'Ollamaを起動し、画像対応モデルをpullしてください。'}</small></>}
      <label>コピーの方向性<select value={copyPreset} onChange={e=>setCopyPreset(e.target.value as typeof copyPreset)}><option value="auto">動画パターンに合わせる</option><option value="engagement">エンゲージメント重視</option><option value="storytelling">ストーリー重視</option><option value="product">商品・サービス訴求</option></select><small className="direction-preview">{copyDirections[copyPreset]}</small></label><label>自由記述<textarea rows={3} placeholder="例：20代向け。旅行先の静けさを強調し、押し売り感は出さない" value={customDirection} onChange={e=>setCustomDirection(e.target.value)}/></label><button className="ai-generate" disabled={!slides.length||aiLoading||(aiProvider!=='chrome'&&!ollamaModel.trim())} onClick={askAi}>{aiLoading?'AIが考えています…':'✦ AIにコピーを提案してもらう'}</button></div>}</section>
  </section><section className="preview-side"><div className="section-head preview-title"><div><span>02</span><h2>プレビュー</h2></div><small>{format.name} · {quality.name}</small></div><div className={`phone pattern-${patternId}`} style={styleVars}><div className="phone-screen">{slides.length?<><img className="hero-image" src={slides[frame.index]?.url} alt="プレビュー" style={{transform:patternTransform(patternFrame),opacity:patternFrame.imageOpacity}}/><div className="scrim" style={{opacity:patternFrame.overlayOpacity}}/><div className="safe-guide"/><div className="reel-copy" style={{opacity:patternFrame.textOpacity,transform:`translateY(${patternFrame.textTranslateY}px) scale(${patternFrame.textScale})`}}><h3>{title||'My story'}</h3>{cta&&<p>{cta}</p>}</div><div className="counter">{frame.index+1} / {slides.length}</div><div className="pattern-badge">{pattern.name}</div></>:<div className="empty-preview"><span>✦</span><p>写真を追加すると<br/>ここにプレビューされます</p></div>}</div></div><div className="transport"><button className="play" disabled={!slides.length} onClick={()=>setPlaying(!playing)}>{playing?'Ⅱ':'▶'}</button><input type="range" min="0" max={total||1} step=".01" value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value))}}/><time>{Math.floor(time)}s / {total}s</time></div><button className="export" disabled={!slides.length||exporting} onClick={exportVideo}>{exporting?'動画を生成中…':'動画を書き出す'}<span>WEBM · {format.width} × {format.height} · {quality.fps}fps</span></button></section></div></main><footer><span>FRAMEFLOW / MULTI-FORMAT EDITION</span><span>外部AIを選択した場合のみ画像を送信します</span></footer></div>
}
